from tkinter import *
window = Tk()
window.title("My Code")
window.minsize(width = 200, height = 400)
window.maxsize(width = 600, height = 1000)
f1 = Frame()
f1.pack()
f2 = Frame()
f2.pack(side = BOTTOM)
l1 = Label(f1, text = "My Label", fg = "Black", bg = "Pink")
l1.pack()
l2 = Label(f2, text = "No value", fg = "Black", bg = "Light Blue")
l2.pack()
window.mainloop()